### ISSUE TITLE
Add `users/bulkUpdateSubscriptions`

### ISSUE THREAD

**Issue by dpolivy** [geoffdutton/iterable-api#100]
Iterable's API supports a `users/bulkUpdateSubscriptions` endpoint which allows one to update subscriptions for multiple users at once. Is it possible to get this supported in this API wrapper?

https://api.iterable.com/api/docs#users_bulkUpdateSubscriptions

I'm happy to look at a PR if that would be helpful in getting this incorporated quickly.

**Comment by geoffdutton** [comment]
This has been released as 1.1.0: https://www.npmjs.com/package/node-iterable-api

Thanks for your contribution!
